name: Package build and Unit tests

on:
  pull_request:
    branches: [ mainline ]
  push:
    branches: [ mainline ]

permissions:
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Create Maven settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: '[{"id": "github", "username": "trjohnny", "password": "${{env.GITHUB_TOKEN}}"}]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
